Iter5
herou3/url-shortener pull request #5
Opened 2023-11-21 11:26 UTC by herou3

Added logic for system var

2023-11-26 09:36 UTC, arttet requested changes
Please add golangci-lint https://github.com/golangci/golangci-lint
Please add a code coverage report https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
Please add gofmt action https://github.com/marketplace/actions/check-code-formatting-using-gofmt

2023-11-26 09:36 UTC, arttet commented on cmd/shortener/main.go
> +	"flag"
Please sort imports
https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package

2023-11-26 09:36 UTC, arttet commented on internal/services/context/context.go
> +		shortURLId = tools.String(8)
Please rename this one
```
tools.String(8)
```

2023-11-26 09:36 UTC, arttet commented on internal/services/handlers/get/get.go
> +var uh = context.GetUH()
Please don't use global variables

2023-11-27 06:31 UTC, herou3 commented on internal/services/context/context.go
> +		shortURLId = tools.String(8)
Changed name

2023-11-28 16:51 UTC, arttet approved these changes
Please add golangci-lint https://github.com/golangci/golangci-lint
Please add gofmt action https://github.com/marketplace/actions/check-code-formatting-using-gofmt

2023-11-28 16:51 UTC, arttet commented on internal/server/server.go
> +func Init() *Server {
Please rename this function

2023-11-28 16:51 UTC, arttet commented on internal/services/handlers/create/create.go
> +func HandleCreateShortURL(response http.ResponseWriter, request *http.Request) {
```suggestion
func CreateShortURLHandler(response http.ResponseWriter, request *http.Request) {
```

2023-11-28 16:51 UTC, arttet commented on internal/services/handlers/create/create.go
> +	isMatch, _ := regexp.MatchString("((http|https)://)(www.)?[a-zA-Z0-9@:%._+~#?&/=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._+~#?&/=]*)", string(fullURL))
It would be better if you add a comment about this reg ex.

2023-12-10 09:58 UTC, closed without merging